version: '3.8'

services:
  backend:
    build:
      context: ./Linux_wallback
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trainproj
      SPRING_DATASOURCE_USERNAME: avinash
      SPRING_DATASOURCE_PASSWORD: Avinash@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
            mysql:
              condition: service_healthy

  frontend:
    build:
      context: ./Linux_wallfront
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ics@0987
      MYSQL_DATABASE: trainproj
      MYSQL_USER: avinash
      MYSQL_PASSWORD: Avinash@123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

